---
title: 'Bios 6301: Final Project'
output: pdf_document
date: "12/07/2020"
---

```{r, echo=FALSE}
library(testthat)
options(
    testthat.default_reporter = "summary",
    testthat.summary.max_reports = Inf
)
source('work.R')
```

```{r}
test_dir('tests')
```

```{r, echo=FALSE}
year <- 20
qb <- file.path('data', sprintf('proj_qb%s.csv', year))
rb <- file.path('data', sprintf('proj_rb%s.csv', year))
wr <- file.path('data', sprintf('proj_wr%s.csv', year))
te <- file.path('data', sprintf('proj_te%s.csv', year))
k <- file.path('data', sprintf('proj_k%s.csv', year))
cur <- file.path('data', sprintf('nfl_current%s.csv', year))

stats <- importProjection(c(qb=qb,rb=rb,wr=wr,te=te,k=k))
obs <- importObserved(cur)
n <- 10
gp <- c(CAR=11, TB=11)
scproj <- scaleByGamesPlayed(stats, n, gp)
best <- topPicks(scproj, pos=c(k=20, qb=20, rb=40, wr=60, te=20))
mdat <- mergeDat(best, obs)
res <- residuals(mdat)
nteams <- 12
cap <- 200
pos <- c(qb=1, rb=2, wr=3, te=1, k=1)
points <- c(fg=4, xpt=1, pass_yds=1/25, pass_tds=4, pass_ints=-2,
             rush_yds=1/10, rush_tds=6, fumbles=-2, rec_yds=1/20, rec_tds=6)

l <- league(stats, nteams, cap, pos, points)
ls <- simleague(1000, res, stats, nteams, cap, pos, points)
cls <- ci(ls)
```

```{r}
l
tryCatch(plot(l), error=function(e) { print('scatterplot') })
tryCatch(boxplot(l), error=function(e) { print('boxplot') })
tryCatch(hist(l), error=function(e) { print('histogram') })
```

```{r}
cls
tryCatch(plot(cls, 'qb'), error=function(e) { print('QB-CI plot') })
tryCatch(plot(cls, 'rb'), error=function(e) { print('RB-CI plot') })
tryCatch(plot(cls, 'wr'), error=function(e) { print('WR-CI plot') })
tryCatch(plot(cls, 'te'), error=function(e) { print('TE-CI plot') })
tryCatch(plot(cls, 'k'), error=function(e) { print('K-CI plot') })
```
